### PR TITLE
Fix limix installation

### PR DESCRIPTION
**Pull request by saketkc**
This is a temporary fix for #12, that forces
user to install numpy, cython before doing pip install limix

### CODE REVIEW

**Comment by saketkc** [comment]
https://travis-ci.org/saketkc/limix/builds/92508647

**Comment by Horta** [comment]
Hi saketkc. Thank you very much for the merge request, and sorry for the late response.

We will be more responsive here from now on and we have made many modifications in how Limix is installed, so hopefully this is not a issue anymore.

Please, let us know if you face any other limix issue.

**Comment by saketkc** [comment]
Hi Daniel, Thanks!

I also uploaded limix to the [bioconda](https://github.com/bioconda/bioconda-recipes) channel a couple of days back.

**Comment by Horta** [comment]
That is great! I saw that Limix was in bioconda but did not know it was one. Thanks!

**Pull request closed without merging**
